spring:
  data:
    elasticsearch:
      uris: http://127.0.0.1:9200

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
